extends: default

rules:
  line-length:
    max: 120
    level: warning

  comments:
    min-spaces-from-content: 1

  comments-indentation: false

  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']